compile:
	g++ -I../includes \
		../src/parser.cpp\
		../src/filesystem.cpp\
		../src/keyvalue.cpp\
		../src/request.cpp\
		../src/router.cpp\
		parser_test.cpp\
		keyvalue_test.cpp\
		tests.cpp -lgtest -lpthread -o tests
